// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext {
        agp_version = '8.10.0'
        kotlin_version = '2.1.0'
    }
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0"
        classpath "org.jetbrains.kotlin:kotlin-serialization:2.1.0"
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
