org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.target.attributes=+export
org.gradle.parallel=true
org.gradle.parallel.warnOnMultipleProjects=notRecommended
org.gradle.caching=true
org.gradle.caching.debug=false
org.gradle.configureondemand=false
android.useAndroidX=true
android.enableR8=true
kotlin.kotlinx.serialization.skip=1
kotlinx.coroutines.debug=off
